"""добавили признак удаления админом

Revision ID: d871355ba87a
Revises: 
Create Date: 2023-03-13 16:48:51.928475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd871355ba87a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('news', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_deleted')
    op.drop_column('news', 'is_published')
    # ### end Alembic commands ###
